# Test action that attempts to generate new docker containers on pull requests

name:  Docker Test

on:
  # push:
  #   branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Docker Test ${{ matrix.mpi }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - mpi: mpich
          - mpi: openmpi
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Create Dockerfile
        run: ./sohpc_setup.sh -c docker-${{ matrix.mpi }}

      - name: Build Docker Image
        run: docker build -t hpc4cmb/sohpc-${{ matrix.mpi }}:temp -f Dockerfile_docker-${{ matrix.mpi }} .

      - name: Test Docker Image
        run: docker run hpc4cmb/sohpc-${{ matrix.mpi }}:temp python -c 'import so3g; from spt3g import core; import sotodlib; import toast.tests; toast.tests.run("env")'

# FIXME:  The "test" above should run the sotodlib test suite, but that is
# not bundled with the package.  We should change that...

